FROM node:lts-alpine3.23

USER node

WORKDIR /home/node/app

COPY --chown=node:node package.json package-lock.json ./

RUN npm ci --omit=dev

COPY --chown=node:node . .

CMD ["sh", "-c", "npm run db:deploy && npm run prod"]