FROM node:22-alpine AS builder

WORKDIR /home/node/app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

FROM node:22-alpine AS runner

USER node 
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev

COPY --chown=node:node src ./src
COPY --chown=node:node prisma.config.js .

COPY --chown=node:node --from=builder \
    /home/node/app/src/shared/database/generated \
    ./src/shared/database/generated

CMD ["node", "./src/main.js"]